server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;
    gzip_min_length 1024;
    gzip_vary on;

    location / {
        try_files $uri $uri/ /index.html;
    }
    location ~* \.(?:jpg|jpeg|png|gif|webp|svg|woff2?|ico)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
    location ~* \.(?:css|js)$ {
        expires 30d;
        add_header Cache-Control "public";
    }
}
